# Generated by Django 3.0.5 on 2020-08-11 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('H_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicantID', models.IntegerField()),
                ('schedule_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('Emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='H_Admin.EmployeeModel')),
            ],
        ),
    ]
