# Generated by Django 3.0.5 on 2020-08-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentModel',
            fields=[
                ('OpportunityCode', models.IntegerField(primary_key=True, serialize=False)),
                ('Qualification', models.CharField(max_length=30)),
                ('Registration_start_date', models.DateField()),
                ('Age_limit', models.IntegerField()),
                ('Last_date_of_apply', models.DateField()),
                ('Department_id', models.CharField(max_length=30)),
                ('No_Of_Positions', models.IntegerField()),
                ('Description', models.CharField(max_length=400)),
                ('Responsibilities', models.CharField(max_length=100)),
                ('Contact_no', models.IntegerField()),
            ],
        ),
    ]
