# Generated by Django 3.0.5 on 2020-08-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=300)),
                ('Designation', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=100)),
                ('Contact_No', models.IntegerField(unique=True)),
                ('EmailID', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
