# Generated by Django 3.0.5 on 2020-08-11 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('RegistrationID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Gender', models.CharField(max_length=30)),
                ('Mobile_No', models.IntegerField(unique=True)),
                ('Address', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationformModel',
            fields=[
                ('ApplicantID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Email_ID', models.EmailField(max_length=254, unique=True)),
                ('Gender', models.CharField(max_length=30)),
                ('Mobile_No', models.IntegerField(unique=True)),
                ('Address', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=30)),
                ('Percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Resume_upload_to', models.FileField(upload_to='resume/')),
                ('status', models.CharField(default=True, max_length=10)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.RecruitmentModel')),
            ],
        ),
    ]
